# Generated by Django 4.2.5 on 2023-10-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название альбома')),
                ('release_date', models.DateTimeField(verbose_name='дата релиза')),
                ('logo', models.ImageField(blank=True, default='media/default_cover.png', null=True, upload_to='album_covers/%Y/', verbose_name='логотип')),
                ('status', models.SmallIntegerField(choices=[(0, 'Обычный'), (1, 'Серебряный'), (2, 'Золотой'), (3, 'Платиновый')], default=0, verbose_name='статус')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удален')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ('release_date',),
            },
        ),
        migrations.CreateModel(
            name='AudioFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип расширения аудио-файла',
                'verbose_name_plural': 'типы расширений аудио-файлов',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название песни')),
                ('audio_file', models.FileField(upload_to='songs/%Y/%m/%d/', verbose_name='аудио файл')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='длительность трека')),
                ('times_played', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество прослушиваний')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='избранное')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.album', verbose_name='альбом')),
                ('genre', models.ManyToManyField(to='main.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='фоловеры')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='псевдоним')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Остальное'), (1, 'Женщина'), (2, 'Мужчина')], default=0, verbose_name='гендер')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.band', verbose_name='группа')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'музыкант',
                'verbose_name_plural': 'музыканты',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.band', verbose_name='группа'),
        ),
    ]
